# Generated by Django 5.0.1 on 2024-03-18 16:22

from django.db import migrations
from django.conf import settings

def create_brokers(apps, schema_editor):
    Broker = apps.get_model("utils", "Broker")

    for broker_name in settings.AVAILABLE_BROKERS:
        Broker.objects.get_or_create(name=broker_name)

def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_brokers, backwards),
    ]

