version: '3.8'

services:
  api:
    container_name: api
    build: .
    # restart: always
    env_file: .env
    command: sh entrypoint.sh
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

  db:
    container_name: db
    image: postgres:14.1-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data_taxer:/var/lib/postgresql/data/

volumes:
  pg_data_taxer: