# Generated by Django 5.0.1 on 2024-08-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsssetTaxSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Asset tax summary ➕',
                'verbose_name_plural': 'Asset tax summaries ➕',
            },
        ),
    ]
