# Generated by Django 5.0.1 on 2024-08-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_summaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asssettaxsummary',
            name='profit_or_loss',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
