# Generated by Django 5.0.1 on 2024-09-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax_calculations', '0005_assettaxcalculation_tax_summary'),
        ('tax_summaries', '0002_asssettaxsummary_profit_or_loss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AsssetTaxSummary',
            new_name='AssetTaxSummary',
        ),
    ]
