# Generated by Django 5.0.1 on 2024-09-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_summaries', '0003_rename_asssettaxsummary_assettaxsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionTaxSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('profit_or_loss', models.FloatField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Option tax summary ➕',
                'verbose_name_plural': 'Option tax summaries ➕',
            },
        ),
    ]
