# Generated by Django 5.0.1 on 2024-09-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_summaries', '0004_optiontaxsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendTaxSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('tax_paid', models.FloatField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dividend tax summary ➕',
                'verbose_name_plural': 'Dividend tax summaries ➕',
            },
        ),
    ]
