# Generated by Django 5.0.1 on 2024-09-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_summaries', '0005_dividendtaxsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralTaxSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('profit_or_loss', models.FloatField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'General tax summary ➕',
                'verbose_name_plural': 'General tax summaries ➕',
            },
        ),
    ]
