# Generated by Django 5.0.1 on 2024-09-14 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_summaries', '0006_generaltaxsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettaxsummary',
            name='general_tax_summary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_tax_summaries', to='tax_summaries.generaltaxsummary'),
        ),
        migrations.AddField(
            model_name='dividendtaxsummary',
            name='general_tax_summary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dividend_tax_summaries', to='tax_summaries.generaltaxsummary'),
        ),
        migrations.AddField(
            model_name='optiontaxsummary',
            name='general_tax_summary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_tax_summaries', to='tax_summaries.generaltaxsummary'),
        ),
    ]
