# Generated by Django 5.0.1 on 2024-09-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_summaries', '0007_assettaxsummary_general_tax_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividendtaxsummary',
            name='profit_or_loss',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
