# Generated by Django 5.0.1 on 2024-03-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_reportfile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRateFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Currency rate file',
                'verbose_name_plural': 'Currency rate files',
            },
        ),
    ]
