# Generated by Django 5.0.1 on 2024-03-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_currencyratefile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
