# Generated by Django 5.0.1 on 2024-03-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_reportfile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyratefile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
