# Generated by Django 5.0.1 on 2024-03-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('usd', models.FloatField()),
                ('eur', models.FloatField()),
                ('gbp', models.FloatField()),
                ('chf', models.FloatField()),
                ('rub', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Currency rate',
                'verbose_name_plural': 'Currency rates',
            },
        ),
    ]
