# Generated by Django 5.0.1 on 2024-03-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyrate',
            options={'verbose_name': 'Currency rate 💹', 'verbose_name_plural': 'Currency rates 💹'},
        ),
    ]
