# Generated by Django 5.0.1 on 2024-01-06 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="previous_day_currency_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="transactions.currencyrate",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("Stocks", "Stocks"),
                    ("Bonds", "Bonds"),
                    ("Equity and Index Options", "Options"),
                    ("ETFs", "ETFs"),
                    ("Forex", "Forex"),
                ],
                max_length=124,
            ),
        ),
    ]
