# Generated by Django 5.0.1 on 2024-01-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=10)),
                ('side', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=8)),
                ('asset_type', models.CharField(choices=[('Stocks', 'Stocks'), ('Bonds', 'Bonds'), ('Options', 'Options'), ('ETFs', 'ETFs')], max_length=20)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('PLN', 'PLN'), ('EUR', 'EUR'), ('RUB', 'RUB')], max_length=3)),
                ('fee', models.FloatField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Import file',
                'verbose_name_plural': 'Import files',
            },
        ),
    ]
