# Generated by Django 5.0.1 on 2024-02-03 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dividend',
            name='withholding_tax',
        ),
        migrations.AddField(
            model_name='transaction',
            name='value_per_share',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='withholding_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='transactions.withholdingtax'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='side',
            field=models.CharField(blank=True, choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=8),
        ),
    ]
