# Generated by Django 5.0.1 on 2024-04-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividendtransaction',
            name='raw_data',
            field=models.CharField(blank=True, max_length=1256, null=True),
        ),
        migrations.AlterField(
            model_name='assettransaction',
            name='asset_type',
            field=models.CharField(choices=[('Stocks', 'Stocks'), ('Dividends', 'Dividends')], max_length=124),
        ),
        migrations.AlterField(
            model_name='dividendtransaction',
            name='asset_type',
            field=models.CharField(choices=[('Stocks', 'Stocks'), ('Dividends', 'Dividends')], max_length=124),
        ),
    ]
