# Generated by Django 5.0.1 on 2024-04-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_dividendtransaction_raw_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividendtransaction',
            name='raw_data',
            field=models.TextField(blank=True, max_length=1256, null=True),
        ),
    ]
