# Generated by Django 5.0.1 on 2024-01-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='option_type',
            field=models.CharField(blank=True, choices=[('CALL', 'CALL'), ('PUT', 'PUT')], max_length=4),
        ),
        migrations.AddField(
            model_name='transaction',
            name='strike_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset_type',
            field=models.CharField(choices=[('Stocks', 'Stocks'), ('Bonds', 'Bonds'), ('Options', 'Equity and Index Options'), ('ETFs', 'ETFs')], max_length=20),
        ),
    ]
