# Generated by Django 5.0.1 on 2024-02-03 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_dividend_withholding_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='withholding_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='transactions.transaction'),
        ),
    ]
