# Generated by Django 5.0.1 on 2024-01-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_transaction_previous_day_currency_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(unique=True)),
                ("revenue", models.FloatField()),
                ("cost", models.FloatField()),
                ("tax", models.FloatField()),
            ],
            options={
                "verbose_name": "Tax calculation",
                "verbose_name_plural": "Tax calculations",
            },
        ),
        migrations.DeleteModel(
            name="Tax",
        ),
    ]
