# Generated by Django 5.0.1 on 2024-02-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_withholding_tax'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dividend',
        ),
    ]
