# Generated by Django 5.0.1 on 2024-01-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_taxcalculation_delete_tax'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaxCalculation',
            new_name='TaxSummary',
        ),
        migrations.AlterModelOptions(
            name='taxsummary',
            options={'verbose_name': 'Tax summary', 'verbose_name_plural': 'Tax summary'},
        ),
    ]
