# Generated by Django 5.0.1 on 2024-01-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='asset',
            field=models.CharField(max_length=124),
        ),
    ]
