# Generated by Django 5.0.1 on 2024-01-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_rename_taxcalculation_taxsummary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revenue", models.FloatField()),
                ("cost", models.FloatField()),
                ("tax", models.FloatField()),
                ("transaction", models.ManyToManyField(to="transactions.transaction")),
            ],
            options={
                "verbose_name": "Tax calculation",
                "verbose_name_plural": "Tax calculations",
            },
        ),
    ]
