# Generated by Django 5.0.1 on 2024-04-14 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_currencyratefile_updated_at'),
        ('rates', '0002_alter_currencyrate_options'),
        ('transactions', '0004_alter_assettransaction_asset_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithholdingTaxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=124)),
                ('asset_type', models.CharField(choices=[('Stocks', 'Stocks'), ('Dividends', 'Dividends'), ('Withholding Tax', 'Withholding Tax')], max_length=124)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GGP', 'GBP'), ('RUB', 'RUB')], max_length=3)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('value_pln', models.FloatField()),
                ('raw_data', models.TextField(blank=True, max_length=1256, null=True)),
                ('previous_day_currency_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='rates.currencyrate')),
                ('report_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='files.reportfile')),
            ],
            options={
                'verbose_name': 'Withholding Tax transaction',
                'verbose_name_plural': 'Withholding Tax transactions',
            },
        ),
        migrations.AddField(
            model_name='dividendtransaction',
            name='withholding_tax_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dividend_transaction', to='transactions.withholdingtaxtransaction'),
        ),
    ]
