# Generated by Django 5.0.1 on 2024-01-08 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0005_taxcalculation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taxcalculation",
            old_name="transaction",
            new_name="transactions",
        ),
    ]
