# Generated by Django 5.0.1 on 2024-01-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='asset_type',
            field=models.CharField(choices=[('Stocks', 'Stocks'), ('Bonds', 'Bonds'), ('Options', 'Equity and Index Options'), ('ETFs', 'ETFs')], max_length=124),
        ),
    ]
