# Generated by Django 5.0.1 on 2024-04-14 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_withholdingtaxtransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividendtransaction',
            name='withholding_tax_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dividend_transaction', to='transactions.withholdingtaxtransaction'),
        ),
    ]
