# Generated by Django 5.0.1 on 2024-01-08 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_rename_transaction_taxcalculation_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxcalculation',
            name='transactions',
        ),
        migrations.AddField(
            model_name='taxcalculation',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='transactions.transaction'),
        ),
    ]
