# Generated by Django 5.0.1 on 2024-04-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_dividendtransaction_withholding_tax_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransaction',
            name='raw_data',
            field=models.TextField(blank=True, max_length=1256, null=True),
        ),
    ]
