# Generated by Django 5.0.1 on 2024-01-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='side',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('asset', 'side', 'price', 'quantity', 'datetime')},
        ),
    ]
