# Generated by Django 5.0.1 on 2024-01-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transaction_side_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='asset_type',
            field=models.CharField(choices=[('Stocks', 'Stocks'), ('Bonds', 'Bonds'), ('Equity and Index Options', 'Options'), ('ETFs', 'ETFs')], max_length=124),
        ),
    ]
