# Generated by Django 5.0.1 on 2024-04-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_assettransaction_raw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettransaction',
            name='asset_type',
            field=models.CharField(choices=[('Stocks', 'Stocks'), ('Options', 'Options'), ('Dividends', 'Dividends'), ('Withholding Tax', 'Withholding Tax')], max_length=124),
        ),
        migrations.AlterField(
            model_name='dividendtransaction',
            name='asset_type',
            field=models.CharField(choices=[('Stocks', 'Stocks'), ('Options', 'Options'), ('Dividends', 'Dividends'), ('Withholding Tax', 'Withholding Tax')], max_length=124),
        ),
        migrations.AlterField(
            model_name='withholdingtaxtransaction',
            name='asset_type',
            field=models.CharField(choices=[('Stocks', 'Stocks'), ('Options', 'Options'), ('Dividends', 'Dividends'), ('Withholding Tax', 'Withholding Tax')], max_length=124),
        ),
    ]
