# Generated by Django 5.0.1 on 2024-04-16 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_currencyratefile_updated_at'),
        ('rates', '0002_alter_currencyrate_options'),
        ('transactions', '0008_alter_assettransaction_asset_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=124)),
                ('asset_type', models.CharField(choices=[('Stocks', 'Stocks'), ('Options', 'Options'), ('Dividends', 'Dividends'), ('Withholding Tax', 'Withholding Tax')], max_length=124)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GGP', 'GBP'), ('RUB', 'RUB')], max_length=3)),
                ('raw_data', models.TextField(blank=True, max_length=1256, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('side', models.CharField(blank=True, choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=8)),
                ('price', models.FloatField()),
                ('fee', models.FloatField()),
                ('quantity', models.FloatField()),
                ('option_type', models.CharField(blank=True, choices=[('CALL', 'CALL'), ('PUT', 'PUT'), ('GGP', 'GBP'), ('RUB', 'RUB')], max_length=4)),
                ('strike_price', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('full_value', models.FloatField(db_comment='Value of assets including fee')),
                ('value_pln', models.FloatField()),
                ('full_value_pln', models.FloatField(db_comment='Value of assets including fee in PLN')),
                ('previous_day_currency_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='rates.currencyrate')),
                ('report_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='files.reportfile')),
            ],
            options={
                'verbose_name': 'Option transaction',
                'verbose_name_plural': 'Option transactions',
                'unique_together': {('asset_name', 'side', 'price', 'quantity', 'executed_at')},
            },
        ),
    ]
