# Generated by Django 5.0.1 on 2024-04-18 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_currencyratefile_updated_at'),
        ('rates', '0002_alter_currencyrate_options'),
        ('transactions', '0010_alter_optiontransaction_option_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettransaction',
            name='asset_type',
            field=models.CharField(choices=[('Stocks', 'Stocks'), ('Options', 'Options'), ('Dividends', 'Dividends'), ('Withholding Tax', 'Withholding Tax'), ('Others', 'Others')], max_length=124),
        ),
        migrations.AlterField(
            model_name='dividendtransaction',
            name='asset_type',
            field=models.CharField(choices=[('Stocks', 'Stocks'), ('Options', 'Options'), ('Dividends', 'Dividends'), ('Withholding Tax', 'Withholding Tax'), ('Others', 'Others')], max_length=124),
        ),
        migrations.AlterField(
            model_name='optiontransaction',
            name='asset_type',
            field=models.CharField(choices=[('Stocks', 'Stocks'), ('Options', 'Options'), ('Dividends', 'Dividends'), ('Withholding Tax', 'Withholding Tax'), ('Others', 'Others')], max_length=124),
        ),
        migrations.AlterField(
            model_name='withholdingtaxtransaction',
            name='asset_type',
            field=models.CharField(choices=[('Stocks', 'Stocks'), ('Options', 'Options'), ('Dividends', 'Dividends'), ('Withholding Tax', 'Withholding Tax'), ('Others', 'Others')], max_length=124),
        ),
        migrations.CreateModel(
            name='InterestRateTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=124)),
                ('asset_type', models.CharField(choices=[('Stocks', 'Stocks'), ('Options', 'Options'), ('Dividends', 'Dividends'), ('Withholding Tax', 'Withholding Tax'), ('Others', 'Others')], max_length=124)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GGP', 'GBP'), ('RUB', 'RUB')], max_length=3)),
                ('raw_data', models.TextField(blank=True, max_length=1256, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('side', models.CharField(blank=True, choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=8)),
                ('value', models.FloatField()),
                ('value_pln', models.FloatField()),
                ('previous_day_currency_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='rates.currencyrate')),
                ('report_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='files.reportfile')),
            ],
            options={
                'verbose_name': 'Interest Rates transaction',
                'verbose_name_plural': 'Interest Rates transactions',
            },
        ),
    ]
