# Generated by Django 5.0.1 on 2024-01-08 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0010_rename_asset_transaction_asset_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxcalculation",
            name="closing_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="as_closing_calculation",
                to="transactions.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="taxcalculation",
            name="opening_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="as_opening_calculation",
                to="transactions.transaction",
            ),
        ),
    ]
