# Generated by Django 5.0.1 on 2024-05-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_assettransaction_asset_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettransaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GGP', 'GBP'), ('RUB', 'RUB'), ('PLN', 'PLN')], max_length=3),
        ),
        migrations.AlterField(
            model_name='dividendtransaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GGP', 'GBP'), ('RUB', 'RUB'), ('PLN', 'PLN')], max_length=3),
        ),
        migrations.AlterField(
            model_name='interestratetransaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GGP', 'GBP'), ('RUB', 'RUB'), ('PLN', 'PLN')], max_length=3),
        ),
        migrations.AlterField(
            model_name='optiontransaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GGP', 'GBP'), ('RUB', 'RUB'), ('PLN', 'PLN')], max_length=3),
        ),
        migrations.AlterField(
            model_name='withholdingtaxtransaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GGP', 'GBP'), ('RUB', 'RUB'), ('PLN', 'PLN')], max_length=3),
        ),
    ]
