# Generated by Django 5.0.1 on 2024-05-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_assettransaction_currency_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assettransaction',
            unique_together={('asset_name', 'side', 'price', 'quantity', 'executed_at', 'raw_data')},
        ),
    ]
