# Generated by Django 5.0.1 on 2024-01-12 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0013_currencyrate_chf"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxcalculation",
            name="quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taxcalculation",
            name="tax_rate",
            field=models.FloatField(default=0.19),
        ),
        migrations.AddField(
            model_name="taxcalculation",
            name="tax_summary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_calculations",
                to="transactions.taxsummary",
            ),
        ),
    ]
