# Generated by Django 5.0.1 on 2024-06-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_assettransaction_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dividendtransaction',
            unique_together={('asset_name', 'value', 'currency', 'executed_at', 'raw_data')},
        ),
    ]
