# Generated by Django 5.0.1 on 2024-06-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_alter_dividendtransaction_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assettransaction',
            options={'verbose_name': 'Asset transaction 💸', 'verbose_name_plural': 'Asset transactions 💸'},
        ),
        migrations.AlterModelOptions(
            name='dividendtransaction',
            options={'verbose_name': 'Dividend transaction 💸', 'verbose_name_plural': 'Dividend transactions 💸'},
        ),
        migrations.AlterModelOptions(
            name='interestratetransaction',
            options={'verbose_name': 'Interest Rates transaction 💸', 'verbose_name_plural': 'Interest Rates transactions 💸'},
        ),
        migrations.AlterModelOptions(
            name='optiontransaction',
            options={'verbose_name': 'Option transaction 💸', 'verbose_name_plural': 'Option transactions 💸'},
        ),
        migrations.AlterModelOptions(
            name='withholdingtaxtransaction',
            options={'verbose_name': 'Withholding Tax transaction 💸', 'verbose_name_plural': 'Withholding Tax transactions 💸'},
        ),
    ]
