# Generated by Django 5.0.1 on 2024-01-20 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_taxcalculation_quantity_taxcalculation_tax_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='previous_day_currency_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='transactions.currencyrate'),
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=124)),
                ('value', models.FloatField()),
                ('value_pln', models.FloatField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('PLN', 'PLN'), ('EUR', 'EUR'), ('RUB', 'RUB')], max_length=3)),
                ('received_at', models.DateTimeField()),
                ('previous_day_currency_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dividends', to='transactions.currencyrate')),
                ('withholding_tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.currencyrate')),
            ],
            options={
                'verbose_name': 'Dividend',
                'verbose_name_plural': 'Dividends',
            },
        ),
    ]
