# Generated by Django 5.0.1 on 2024-06-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_alter_assettransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiontransaction',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
