# Generated by Django 5.0.1 on 2024-01-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_alter_transaction_previous_day_currency_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='received_at',
            field=models.DateField(),
        ),
    ]
