# Generated by Django 5.0.1 on 2024-06-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_optiontransaction_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiontransaction',
            name='base_instrument',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
