# Generated by Django 5.0.1 on 2024-01-23 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_alter_dividend_received_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithholdingTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=124)),
                ('value', models.FloatField()),
                ('value_pln', models.FloatField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('PLN', 'PLN'), ('EUR', 'EUR'), ('RUB', 'RUB')], max_length=3)),
                ('paid_at', models.DateField()),
                ('previous_day_currency_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='withholding_taxes', to='transactions.currencyrate')),
            ],
            options={
                'verbose_name': 'Withholding Tax',
                'verbose_name_plural': 'Withholding Taxes',
            },
        ),
        migrations.AlterField(
            model_name='dividend',
            name='withholding_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='transactions.withholdingtax'),
        ),
    ]
