# Generated by Django 5.0.1 on 2024-01-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_withholdingtax_alter_dividend_withholding_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='value_per_share',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
