# Generated by Django 5.0.1 on 2024-06-26 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_alter_optiontransaction_base_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiontransaction',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
