# Generated by Django 5.0.1 on 2024-06-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_optiontransaction_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiontransaction',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
