# Generated by Django 5.0.1 on 2024-06-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_alter_optiontransaction_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiontransaction',
            name='closing',
            field=models.BooleanField(default=False),
        ),
    ]
