# Generated by Django 5.0.1 on 2024-06-02 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_calculations', '0001_initial'),
        ('transactions', '0015_alter_assettransaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendTaxCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.FloatField()),
                ('cost', models.FloatField()),
                ('profit_or_loss', models.FloatField()),
                ('tax_rate', models.FloatField(default=0.19)),
                ('tax', models.FloatField()),
                ('dividend_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_calculation', to='transactions.dividendtransaction')),
                ('withholding_tax_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_calculation', to='transactions.withholdingtaxtransaction')),
            ],
            options={
                'verbose_name': 'Dividend tax calculation 🧮',
                'verbose_name_plural': 'Dividend tax calculations 🧮',
            },
        ),
    ]
