# Generated by Django 5.0.1 on 2024-06-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_calculations', '0003_optiontaxcalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiontaxcalculation',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
