# Generated by Django 5.0.1 on 2024-08-13 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_calculations', '0004_optiontaxcalculation_quantity'),
        ('tax_summaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettaxcalculation',
            name='tax_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_calculations', to='tax_summaries.asssettaxsummary'),
        ),
    ]
