# Generated by Django 5.0.1 on 2024-09-03 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_calculations', '0005_assettaxcalculation_tax_summary'),
        ('tax_summaries', '0004_optiontaxsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiontaxcalculation',
            name='tax_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_calculations', to='tax_summaries.optiontaxsummary'),
        ),
    ]
