# Generated by Django 5.0.1 on 2024-09-18 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_calculations', '0007_dividendtaxcalculation_tax_summary'),
        ('transactions', '0022_remove_optiontransaction_closing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestRateTaxCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.FloatField()),
                ('cost', models.FloatField()),
                ('profit_or_loss', models.FloatField()),
                ('tax_rate', models.FloatField(default=0.19)),
                ('tax', models.FloatField()),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('interest_rate_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_calculation', to='transactions.interestratetransaction')),
            ],
            options={
                'verbose_name': 'Interest rate tax calculation 🧮',
                'verbose_name_plural': 'Interest rate tax calculations 🧮',
            },
        ),
    ]
