# Generated by Django 5.0.1 on 2024-09-29 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_calculations', '0008_interestratetaxcalculation'),
        ('tax_summaries', '0009_interestratetaxsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestratetaxcalculation',
            name='tax_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_calculations', to='tax_summaries.interestratetaxsummary'),
        ),
    ]
